FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY backend ./

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "eventsearch.wsgi"]
